/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import conexionSQL.conexionSQL;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SENA
 */
public class sistema extends javax.swing.JFrame {

    conexionSQL cc=new conexionSQL();
    Connection con=cc.conexion();
    public sistema() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(getBackground());
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jlabel1 = new javax.swing.JLabel();
        jlabel2 = new javax.swing.JLabel();
        Documento = new java.awt.TextField();
        jlabel3 = new javax.swing.JLabel();
        Nombres = new java.awt.TextField();
        jlabel4 = new javax.swing.JLabel();
        jlabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Direccion = new java.awt.TextField();
        Celular = new java.awt.TextField();
        btnNuevo = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();
        Genero = new javax.swing.JComboBox<>();
        TipoDocumento = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAprendiz = new javax.swing.JTable();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jlabel1.setText("TipoDocumento");

        jlabel2.setText("Documento");

        jlabel3.setText("Nombres");

        jlabel4.setText("Genero");

        jlabel5.setText("Direccion");

        jLabel6.setText("Celular");

        Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formularios/icons8-new-button-48.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formularios/icons8-guardar-50.png"))); // NOI18N
        BtnGuardar.setText("guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formularios/icons8-eliminar-propiedad-50.png"))); // NOI18N
        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formularios/icons8-aprobar-y-actualizar-50.png"))); // NOI18N
        BtnActualizar.setText("Actualizar");
        BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarActionPerformed(evt);
            }
        });

        Genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mujer", "hombre", "otro" }));
        Genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroActionPerformed(evt);
            }
        });

        TipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula ciudadania", "tarjeta de identidad" }));
        TipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDocumentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Direccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Genero, javax.swing.GroupLayout.Alignment.LEADING, 0, 132, Short.MAX_VALUE))
                    .addComponent(Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(BtnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel1)
                    .addComponent(TipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlabel2)
                    .addComponent(Documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlabel3)
                    .addComponent(Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel4)
                    .addComponent(Genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlabel5)
                    .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardar)
                    .addComponent(btnNuevo)
                    .addComponent(BtnEliminar)
                    .addComponent(BtnActualizar))
                .addGap(59, 59, 59))
        );

        jLabel1.setText("Buscar:");

        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        tablaAprendiz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaAprendiz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaAprendiz.setSelectionBackground(new java.awt.Color(102, 102, 102));
        tablaAprendiz.setShowGrid(true);
        tablaAprendiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAprendizMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaAprendiz);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoDocumentoActionPerformed

    private void DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
         insertarDatos();
         limpiarCajas();
         mostrarDatos();
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        filtrarDatos(Buscar.getText());
    }//GEN-LAST:event_BuscarActionPerformed

    private void GeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneroActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiarCajas();
        mostrarDatos();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tablaAprendizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAprendizMouseClicked
        
        int filaSeleccionada=tablaAprendiz.rowAtPoint(evt.getPoint());
        TipoDocumento.setSelectedItem(tablaAprendiz.getValueAt(filaSeleccionada,0));
        Documento.setText(tablaAprendiz.getValueAt(filaSeleccionada,1).toString());
        Nombres.setText(tablaAprendiz.getValueAt(filaSeleccionada,2).toString());
        Genero.setSelectedItem(tablaAprendiz.getValueAt(filaSeleccionada,3));
        Direccion.setText(tablaAprendiz.getValueAt(filaSeleccionada,4).toString());
        Celular.setText(tablaAprendiz.getValueAt(filaSeleccionada,5).toString());
    }//GEN-LAST:event_tablaAprendizMouseClicked

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        actualizarDatos();
        limpiarCajas();
        mostrarDatos();
    }//GEN-LAST:event_BtnActualizarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        eliminarRegistro();
        mostrarDatos();
        limpiarCajas();
        
    }//GEN-LAST:event_BtnEliminarActionPerformed
    
    public void insertarDatos(){
    
    try{
        String SQL="insert into aprendiz(tipo_doc,documento,nombre,genero,direccion,celular) values(?,?,?,?,?,?)";
       java.sql.PreparedStatement pst= con.prepareStatement(SQL);
       
        int seleccionado = TipoDocumento.getSelectedIndex();
        pst.setString(1,TipoDocumento.getItemAt(seleccionado));
        
        pst.setDouble(2, Double.parseDouble(Documento.getText()));
        pst.setString(3, Nombres.getText());
        
        int seleccionado1= Genero.getSelectedIndex();
        pst.setString(4, Genero.getItemAt(seleccionado1));
        
        pst.setString(5, Direccion.getText());
        pst.setDouble(6,Double.parseDouble(Celular.getText() ));
        
        pst.execute();
        JOptionPane.showMessageDialog(null, "Datos registrados correctamente");
        
        
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,"Error de registro"+e.getMessage());
    }
}
    
public void limpiarCajas(){
    TipoDocumento.setSelectedItem(null);
    Documento.setText(null);
    Nombres.setText(null);
    Genero.setSelectedItem(null);
    Direccion.setText(null);
    Celular.setText(null);
}

public void mostrarDatos(){
    //titulos
    
    String[] titulos={"TIPO","DOCUMENTO","NOMBRES","GENERO","DIRECCION","TELEFONO"};
    String [] registros= new String[7];
    
    DefaultTableModel modelo=new DefaultTableModel(null,titulos);
    
    String SQL= "select * from aprendiz";
    
    //llena las filas cuando se consulta
    
    try{
        java.sql.Statement st=con.createStatement();
        java.sql.ResultSet rs= st.executeQuery(SQL);
        
        while (rs.next()){
            registros[0]=rs.getString("Tipo_doc");
            registros[1]=rs.getString("documento");
            registros[2]=rs.getString("nombre");
            registros[3]=rs.getString("genero");
            registros[4]=rs.getString("direccion");
            registros[5]=rs.getString("celular");
        modelo.addRow(registros);
        }
        tablaAprendiz.setModel(modelo);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Error de busqueda"+e.getMessage());
    }
}    
    
public void actualizarDatos(){
    
    try{
        String SQL= "update aprendiz set tipo_doc=?,documento=?,nombre=?,genero=?,direccion=?,celular=? where documento=?";
        int filaSeleccionada=tablaAprendiz.getSelectedRow();
        String ref=(String)tablaAprendiz.getValueAt(filaSeleccionada,1);
        
        
        java.sql.PreparedStatement pst=con.prepareStatement(SQL);
        int seleccionado= TipoDocumento.getSelectedIndex();
        pst.setString(1,TipoDocumento.getItemAt(seleccionado));
        
        pst.setDouble(2, Double.parseDouble(Documento.getText()));
        pst.setString(3, Nombres.getText());
        
        int seleccionado1= Genero.getSelectedIndex();
        pst.setString(4,Genero.getItemAt(seleccionado));
        
        pst.setString(5, Direccion.getText());
        pst.setDouble(6, Double.parseDouble(Celular.getText()));
        
        pst.setString(7, ref);
        pst.execute();
        JOptionPane.showMessageDialog(null, "Datos actualizados correctamente");
        
    }catch (Exception e){
        JOptionPane.showMessageDialog(null, "Eror de Actualizacion"+e.getMessage());
    }
    
}

public void eliminarRegistro(){
    int filaSeleccionada=tablaAprendiz.getSelectedRow();
    
    try{
        String SQL="delete from aprendiz where documento="+tablaAprendiz.getValueAt(filaSeleccionada,1);
        
        java.sql.Statement st= con.createStatement();
        
        int n=st.executeUpdate(SQL);
        
        if(n>=0){
            JOptionPane.showMessageDialog(null, "Registro eliminado");
        }
    }catch (Exception e){
        JOptionPane.showMessageDialog(null, "Error al eliminar registro"+ e.getMessage());
    }
}

public void filtrarDatos(String valor){
    //Crear los Titulos
    String[] titulos={"TIPO","DOCUMENTO","NOMBRES","GENERO","DIRECCION","TELEFONO"};
    String [] registros= new String[7];
    
    DefaultTableModel modelo=new DefaultTableModel(null,titulos);
    
    String SQL= "select * from aprendiz where nombre like '%"+valor+"%' or documento like '%"+valor+"%'";
       //que llene las filas cuando consulto
       
       try{
           java.sql.Statement st= con.createStatement();
           java.sql.ResultSet rs=st.executeQuery(SQL);
           
           while(rs.next()){
              registros[0]=rs.getString("Tipo_doc");
            registros[1]=rs.getString("documento");
            registros[2]=rs.getString("nombre");
            registros[3]=rs.getString("genero");
            registros[4]=rs.getString("direccion");
            registros[5]=rs.getString("celular");
            modelo.addRow(registros);
           }
           tablaAprendiz.setModel(modelo);
       }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error registro"+ e.getMessage());
       }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JTextField Buscar;
    private java.awt.TextField Celular;
    private java.awt.TextField Direccion;
    private java.awt.TextField Documento;
    private javax.swing.JComboBox<String> Genero;
    private java.awt.TextField Nombres;
    private javax.swing.JComboBox<String> TipoDocumento;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JTable tablaAprendiz;
    // End of variables declaration//GEN-END:variables
}
